apiVersion: "greenplum.pivotal.io/v1"
kind: "GreenplumCluster"
metadata:
  name: my-greenplum
spec:
  masterAndStandby:
    standby: "yes"
    hostBasedAuthentication: |
      # host   all   gpadmin   1.2.3.4/32   trust
      # host   all   gpuser    0.0.0.0/0   md5
    memory: "800Mi"
    cpu: "0.5"
    storage: 1G
    storageClassName: local-storage
    antiAffinity: "no"
  segments:
    primarySegmentCount: 1
    memory: "800Mi"
    cpu: "0.5"
    storage: 1G
    storageClassName: local-storage
    antiAffinity: "no"
    mirros: yes
