---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: greenplum-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
